# version: "3.9"

services:
  backend:
    build: ./backend
    container_name: todo1_backend
    ports:
      - "8000:8000" # expose to host
    env_file:
      - ./backend/.env
    restart: unless-stopped


  frontend:
    build: ./frontend
    container_name: todo1_frontend
    ports:
      - "3000:3000" # expose to host
    depends_on:
      - backend
    restart: unless-stopped


  # db:
  #   image: postgres:18
  #   container_name: postgres_db
  #   environment:
  #     - POSTGRES_DB=todo_db
  #     - POSTGRES_USER=todo_user
  #     - POSTGRES_PASSWORD=todo_pass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: